name: openvpn

on:
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenVPN
        run: |
          sudo apt-get update || true
          sudo apt install -y openvpn openvpn-systemd-resolved
