name: openvpn

on:
  workflow_dispatch:
jobs:
  deployment:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
