name: openvpn

on:
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenVPN
        run: |
          sudo rm -f /etc/apt/sources.list.d/archive_uri-*
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
